### MENDAPATKAN SEMUA DATA RULE
GET http://localhost:4000/api/rules

### MEMBUAT RULE BARU
POST http://localhost:4000/api/rules
Content-Type: application/json

{
    "kodeBidang" : "B01",
    "kodePekerjaan" : "P01",
    "kodeKriteria" : "K01,K03"
}