### MENDAPATKAN SEMUA DATA USER
GET http://localhost:4000/api/users

### MENDAPATKAN  DATA USER BERDASARKAN ID
GET http://localhost:4000/api/users/4

### MEMBUAT USER BARU
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name" : "user 2",
    "email" : "user2@gmail.com",
    "password" : "kesehatan",
    "re_password" : "kesehatan"
}

### UPDATE DATA USER
PATCH http://localhost:4000/api/users/4
Content-Type: application/json

{
    "name" : "user 2 update",
    "password" : "kesehatan",
    "re_password" : "kesehatan"
}

### DELETE DATA USER
DELETE http://localhost:4000/api/users/3

### LOGIN
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
    "email" : "user10@gmail.com",
    "password" : "kesehatan1"
}